version: '3.8'

services:
  # 1. 🐘 PostgreSQL база данных
  postgres:
    image: postgres:16-alpine
    container_name: petpassport-db
    environment:
      POSTGRES_DB: PetPassportDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - petpassport-network

  # 2. 🖥️ ASP.NET Core приложение (API)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petpassport-api
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=PetPassportDb;Username=postgres;Password=${POSTGRES_PASSWORD}"
      BotService__BaseUrl: "http://telegram-bot:8080"
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      CORS_ORIGINS: "${CORS_ORIGINS}"
      ASPNETCORE_ENVIRONMENT: Production
      BOT_TOKEN: "${BOT_TOKEN}"
      Email__SmtpHost: "${Email__SmtpHost}"
      Email__SmtpPort: "${Email__SmtpPort}"
      Email__Username: "${Email__Username}"
      Email__Password: "${Email__Password}"
      Email__SupportEmail: "${Email__SupportEmail}"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/wwwroot/uploads
    networks:
      - petpassport-network

  # 3. 🤖 Python Bot (Aiohttp)
  telegram-bot:
    build:
      context: ./PetPassport-TgBot
      dockerfile: Dockerfile
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEB_HOOK_URL=${WEB_HOOK_URL}
      - WEB_HOOK_PATH=${WEB_HOOK_PATH}
      - WEB_SERVER_HOST=${WEB_SERVER_HOST}
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8080
      - BASE_URL=${BASE_URL}
      - SERVER_URL=${SERVER_URL}
    volumes:
      - ./img:/app/img
    networks:
      - petpassport-network

  # 4. 🌐 Frontend (React + Nginx)
  frontend:
    build:
      context: ../Pet_Passport/front
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_TG_BOT_URL: ${VITE_TG_BOT_URL}
        VITE_RUSTORE_URL: ${VITE_RUSTORE_URL}
    container_name: petpassport-frontend
    depends_on:
      - api
    networks:
      - petpassport-network

  # 5. 🔀 Nginx (reverse proxy)
  nginx:
    image: nginx:alpine
    container_name: petpassport-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "4443:4443"
      - "8443:8443"
    volumes:
      - ./deploy/nginx/mypetpassport.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
      - frontend
      - telegram-bot
    networks:
      - petpassport-network

volumes:
  postgres_data:

networks:
  petpassport-network:
    driver: bridge
