// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetPassport.Data;

#nullable disable

namespace PetPassport.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201204944_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetPassport.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramNick")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("PetPassport.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetPassport.Models.PetEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsReminderSent")
                        .HasColumnType("boolean");

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReminderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ReminderEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("ReminderUnit")
                        .HasColumnType("integer");

                    b.Property<int?>("ReminderValue")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Events");

                    b.HasDiscriminator<string>("EventType").HasValue("Base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PetPassport.Models.PetPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.Property<string>("TelegramFileId")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("PetPhotos");
                });

            modelBuilder.Entity("PetPassport.Models.DoctorVisitEvent", b =>
                {
                    b.HasBaseType("PetPassport.Models.PetEvent");

                    b.Property<string>("Clinic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<string>("Doctor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recommendations")
                        .HasColumnType("text");

                    b.Property<string>("Referrals")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("DoctorVisit");
                });

            modelBuilder.Entity("PetPassport.Models.VaccineEvent", b =>
                {
                    b.HasBaseType("PetPassport.Models.PetEvent");

                    b.Property<string>("Medicine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextVaccinationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PeriodUnit")
                        .HasColumnType("integer");

                    b.Property<int?>("PeriodValue")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Vaccine");
                });

            modelBuilder.Entity("TreatmentEvent", b =>
                {
                    b.HasBaseType("PetPassport.Models.PetEvent");

                    b.Property<DateTime?>("NextTreatmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Parasite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PeriodUnit")
                        .HasColumnType("integer");

                    b.Property<int?>("PeriodValue")
                        .HasColumnType("integer");

                    b.Property<string>("Remedy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Events", t =>
                        {
                            t.Property("PeriodUnit")
                                .HasColumnName("TreatmentEvent_PeriodUnit");

                            t.Property("PeriodValue")
                                .HasColumnName("TreatmentEvent_PeriodValue");
                        });

                    b.HasDiscriminator().HasValue("Treatment");
                });

            modelBuilder.Entity("PetPassport.Models.Pet", b =>
                {
                    b.HasOne("PetPassport.Models.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PetPassport.Models.PetEvent", b =>
                {
                    b.HasOne("PetPassport.Models.Pet", null)
                        .WithMany("Events")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetPassport.Models.PetPhoto", b =>
                {
                    b.HasOne("PetPassport.Models.Pet", "Pet")
                        .WithMany("Photos")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetPassport.Models.Owner", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetPassport.Models.Pet", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
